"""Professor column in Movie table added.

Revision ID: 40a0960170c9
Revises: 5007adb40bcd
Create Date: 2023-05-23 21:57:54.761389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a0960170c9'
down_revision = '5007adb40bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professor', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('professor')

    # ### end Alembic commands ###
