"""Tabless Lesson, Attendance adjustmens.

Revision ID: acfb22ed042c
Revises: df553c8b4d83
Create Date: 2023-05-25 02:28:08.461747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acfb22ed042c'
down_revision = 'df553c8b4d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('professor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professor', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
