"""column movie.discipline added in movie Table.

Revision ID: df553c8b4d83
Revises: 40a0960170c9
Create Date: 2023-05-24 15:39:09.835731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df553c8b4d83'
down_revision = '40a0960170c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discipline', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('discipline')

    # ### end Alembic commands ###
